import { useMemo, useState } from 'react'
import CATALOGUE from '../../../13-design-patterns/patterns.json'

/**
 * The pattern browser.
 *
 * Data comes from patterns.json, which is generated by
 * scripts/gen_pattern_catalogue.py from the same tables that produce
 * CATALOGUE.md. CI fails if the two drift, so a pattern cannot say one thing on
 * the page and another thing here.
 *
 * The two fields worth the screen space are `bridge` (what this pattern becomes
 * once it crosses a network) and `top1` (what an experienced engineer does that
 * a competent one does not). Everything else is available in any reference.
 */

/**
 * The bridge, drawn rather than described.
 *
 * Every GoF pattern's distributed counterpart is harder for the same reason:
 * the single-process version quietly relies on shared memory and one clock, and
 * the distributed version has neither. Two boxes and an arrow say that faster
 * than the paragraph does -- and the paragraph is still there underneath.
 */
/**
 * Greedy word wrap to at most `max` lines of roughly `per` characters.
 *
 * The first version never flushed the final line, so any text short enough to
 * fit on one line came back as an EMPTY array -- "Adapter" rendered as a blank
 * box -- and "Template Method" came back as ["Method"], silently dropping a
 * word. Both bugs survived a verification pass because that pass only checked
 * the multi-word `bridge` strings and never the `name` side.
 *
 * This version cannot lose text: when the line budget runs out, everything
 * remaining is appended to the last line rather than discarded.
 */
function wrap(text, per, max) {
  const words = String(text).split(' ').filter(Boolean)
  if (!words.length) return []

  const lines = []
  let line = words[0]

  for (let i = 1; i < words.length; i++) {
    const candidate = `${line} ${words[i]}`
    if (candidate.length <= per) {
      line = candidate
      continue
    }
    if (lines.length === max - 1) {
      // Out of lines: the remainder joins this one rather than vanishing.
      line = `${line} ${words.slice(i).join(' ')}`
      break
    }
    lines.push(line)
    line = words[i]
  }

  lines.push(line)
  return lines
}

function BridgeDiagram({ name, bridge }) {
  // Wrap rather than truncate. The first version cut at 30 characters, so
  // "Leader election - distributed lock" rendered as "...distributed..." with
  // the full string repeated immediately below it -- an ellipsis and a
  // duplicate, neither of which the reader needed.
  const left = wrap(name, 20, 3)
  const right = wrap(bridge, 22, 3)
  const rows = Math.max(left.length, right.length)
  const boxH = rows === 1 ? 40 : rows === 2 ? 52 : 64
  const h = boxH + 34
  const midY = 20 + boxH / 2

  const lines = (arr, x, cls) =>
    arr.map((ln, i) => (
      <text
        key={i}
        className={cls}
        x={x}
        y={20 + boxH / 2 + (i - (arr.length - 1) / 2) * 15 + 4.5}
        textAnchor="middle"
      >
        {ln}
      </text>
    ))

  return (
    <svg className="bridge-svg" viewBox={`0 0 460 ${h}`} role="img"
         aria-label={`In one process: ${name}. Across a network: ${bridge}.`}>
      <rect className="bridge-box" x="1" y="20" width="176" height={boxH} rx="7" />
      <text className="bridge-cap" x="89" y="14" textAnchor="middle">IN ONE PROCESS</text>
      {lines(left, 89, 'bridge-txt')}

      <line className="bridge-arrow" x1="182" y1={midY} x2="272" y2={midY}
            markerEnd="url(#bridge-tip)" />
      <text className="bridge-cap mid" x="227" y={midY - 8} textAnchor="middle">no shared memory</text>
      <text className="bridge-cap mid" x="227" y={midY + 16} textAnchor="middle">no shared clock</text>

      <rect className="bridge-box to" x="278" y="20" width="181" height={boxH} rx="7" />
      <text className="bridge-cap to" x="368" y="14" textAnchor="middle">ACROSS A NETWORK</text>
      {lines(right, 368, 'bridge-txt to')}

      <defs>
        <marker id="bridge-tip" viewBox="0 0 10 10" refX="9" refY="5"
                markerWidth="6" markerHeight="6" orient="auto-start-reverse">
          <path d="M0,0 L10,5 L0,10 z" className="bridge-tip" />
        </marker>
      </defs>
    </svg>
  )
}

export default function Patterns() {
  const [familyId, setFamilyId] = useState(CATALOGUE.families[0].id)
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState(CATALOGUE.families[0].patterns[0].name)

  const family = CATALOGUE.families.find(f => f.id === familyId) ?? CATALOGUE.families[0]

  // Searching spans every family -- looking for "retry" should not require
  // knowing which of five families it was filed under.
  const results = useMemo(() => {
    const q = query.trim().toLowerCase()
    if (!q) return family.patterns.map(p => ({ ...p, family: family.name }))
    return CATALOGUE.families.flatMap(f =>
      f.patterns
        .filter(p =>
          p.name.toLowerCase().includes(q) ||
          (p.what ?? '').toLowerCase().includes(q) ||
          (p.bridge ?? '').toLowerCase().includes(q))
        .map(p => ({ ...p, family: f.name })),
    )
  }, [query, family])

  const active = results.find(p => p.name === selected) ?? results[0] ?? null

  const total = CATALOGUE.families.reduce((n, f) => n + f.patterns.length, 0)

  return (
    <div className="patterns">
      <div className="pat-side">
        <input
          className="pat-search"
          type="search"
          placeholder={`Search ${total} patterns…`}
          value={query}
          onChange={e => setQuery(e.target.value)}
          aria-label="Search patterns"
        />

        {!query && (
          <div className="pat-fams">
            {CATALOGUE.families.map(f => (
              <button
                key={f.id}
                className={f.id === familyId ? 'tick on' : 'tick'}
                onClick={() => { setFamilyId(f.id); setSelected(f.patterns[0].name) }}
              >
                {f.name.replace('Gang of Four — ', 'GoF ')} <span>{f.patterns.length}</span>
              </button>
            ))}
          </div>
        )}

        <ul className="pat-list">
          {results.map(p => (
            <li key={`${p.family}-${p.name}`}>
              <button
                className={active && p.name === active.name ? 'pat-item on' : 'pat-item'}
                onClick={() => setSelected(p.name)}
              >
                <strong>{p.name}</strong>
                {query && <em>{p.family}</em>}
              </button>
            </li>
          ))}
          {!results.length && <li className="hint">Nothing matches “{query}”.</li>}
        </ul>
      </div>

      <div className="pat-detail">
        {!active && <p className="hint">Select a pattern.</p>}
        {active && (
          <>
            <h2>{active.name}</h2>
            <p className="pat-what">{active.what}</p>

            {active.bridge && (
              <div className="pat-bridge">
                <BridgeDiagram name={active.name} bridge={active.bridge} />
                <p>{active.harder}</p>
              </div>
            )}

            <dl className="pat-fields">
              {active.where && (<><dt>Where</dt><dd>{active.where}</dd></>)}
              {active.how && (<><dt>How</dt><dd>{active.how}</dd></>)}
              {active.why && (<><dt>Why</dt><dd>{active.why}</dd></>)}
              {active.adv && (<><dt>Advantages</dt><dd>{active.adv}</dd></>)}
              {active.dis && (<><dt>Disadvantages</dt><dd>{active.dis}</dd></>)}
              {active.level && (<><dt>Difficulty</dt><dd>{active.level}</dd></>)}
            </dl>

            {active.tradeoff && (
              <p className="pat-tradeoff"><span>Trade-off</span> {active.tradeoff}</p>
            )}

            {active.top1 && (
              <div className="pat-top1">
                <span className="pat-top1-h">What the top 1% do differently</span>
                <p>{active.top1}</p>
              </div>
            )}

            {!active.top1 && (
              <p className="hint">
                Indexed here; the full entry lands as this family is written out. See the
                catalogue in the repository.
              </p>
            )}
          </>
        )}
      </div>
    </div>
  )
}
