import { useMemo, useState } from 'react'
import CATALOGUE from '../../../13-design-patterns/patterns.json'

/**
 * The pattern browser.
 *
 * Data comes from patterns.json, which is generated by
 * scripts/gen_pattern_catalogue.py from the same tables that produce
 * CATALOGUE.md. CI fails if the two drift, so a pattern cannot say one thing on
 * the page and another thing here.
 *
 * The two fields worth the screen space are `bridge` (what this pattern becomes
 * once it crosses a network) and `top1` (what an experienced engineer does that
 * a competent one does not). Everything else is available in any reference.
 */
export default function Patterns() {
  const [familyId, setFamilyId] = useState(CATALOGUE.families[0].id)
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState(CATALOGUE.families[0].patterns[0].name)

  const family = CATALOGUE.families.find(f => f.id === familyId) ?? CATALOGUE.families[0]

  // Searching spans every family -- looking for "retry" should not require
  // knowing which of five families it was filed under.
  const results = useMemo(() => {
    const q = query.trim().toLowerCase()
    if (!q) return family.patterns.map(p => ({ ...p, family: family.name }))
    return CATALOGUE.families.flatMap(f =>
      f.patterns
        .filter(p =>
          p.name.toLowerCase().includes(q) ||
          (p.what ?? '').toLowerCase().includes(q) ||
          (p.bridge ?? '').toLowerCase().includes(q))
        .map(p => ({ ...p, family: f.name })),
    )
  }, [query, family])

  const active = results.find(p => p.name === selected) ?? results[0] ?? null

  const total = CATALOGUE.families.reduce((n, f) => n + f.patterns.length, 0)

  return (
    <div className="patterns">
      <div className="pat-side">
        <input
          className="pat-search"
          type="search"
          placeholder={`Search ${total} patterns…`}
          value={query}
          onChange={e => setQuery(e.target.value)}
          aria-label="Search patterns"
        />

        {!query && (
          <div className="pat-fams">
            {CATALOGUE.families.map(f => (
              <button
                key={f.id}
                className={f.id === familyId ? 'tick on' : 'tick'}
                onClick={() => { setFamilyId(f.id); setSelected(f.patterns[0].name) }}
              >
                {f.name.replace('Gang of Four — ', 'GoF ')} <span>{f.patterns.length}</span>
              </button>
            ))}
          </div>
        )}

        <ul className="pat-list">
          {results.map(p => (
            <li key={`${p.family}-${p.name}`}>
              <button
                className={active && p.name === active.name ? 'pat-item on' : 'pat-item'}
                onClick={() => setSelected(p.name)}
              >
                <strong>{p.name}</strong>
                {query && <em>{p.family}</em>}
              </button>
            </li>
          ))}
          {!results.length && <li className="hint">Nothing matches “{query}”.</li>}
        </ul>
      </div>

      <div className="pat-detail">
        {!active && <p className="hint">Select a pattern.</p>}
        {active && (
          <>
            <h2>{active.name}</h2>
            <p className="pat-what">{active.what}</p>

            {active.bridge && (
              <div className="pat-bridge">
                <span className="pat-bridge-h">Across a network this becomes</span>
                <strong>{active.bridge}</strong>
                <p>{active.harder}</p>
              </div>
            )}

            <dl className="pat-fields">
              {active.where && (<><dt>Where</dt><dd>{active.where}</dd></>)}
              {active.how && (<><dt>How</dt><dd>{active.how}</dd></>)}
              {active.why && (<><dt>Why</dt><dd>{active.why}</dd></>)}
              {active.adv && (<><dt>Advantages</dt><dd>{active.adv}</dd></>)}
              {active.dis && (<><dt>Disadvantages</dt><dd>{active.dis}</dd></>)}
              {active.level && (<><dt>Difficulty</dt><dd>{active.level}</dd></>)}
            </dl>

            {active.tradeoff && (
              <p className="pat-tradeoff"><span>Trade-off</span> {active.tradeoff}</p>
            )}

            {active.top1 && (
              <div className="pat-top1">
                <span className="pat-top1-h">What the top 1% do differently</span>
                <p>{active.top1}</p>
              </div>
            )}

            {!active.top1 && (
              <p className="hint">
                Indexed here; the full entry lands as this family is written out. See the
                catalogue in the repository.
              </p>
            )}
          </>
        )}
      </div>
    </div>
  )
}
