import { useMemo, useState } from 'react'
import CATALOGUE from '../../../13-design-patterns/patterns.json'

/**
 * The pattern browser.
 *
 * Data comes from patterns.json, which is generated by
 * scripts/gen_pattern_catalogue.py from the same tables that produce
 * CATALOGUE.md. CI fails if the two drift, so a pattern cannot say one thing on
 * the page and another thing here.
 *
 * The two fields worth the screen space are `bridge` (what this pattern becomes
 * once it crosses a network) and `top1` (what an experienced engineer does that
 * a competent one does not). Everything else is available in any reference.
 */

/**
 * The bridge, drawn rather than described.
 *
 * Every GoF pattern's distributed counterpart is harder for the same reason:
 * the single-process version quietly relies on shared memory and one clock, and
 * the distributed version has neither. Two boxes and an arrow say that faster
 * than the paragraph does -- and the paragraph is still there underneath.
 */
function BridgeDiagram({ name, bridge }) {
  return (
    <svg className="bridge-svg" viewBox="0 0 460 74" role="img"
         aria-label={`In one process: ${name}. Across a network: ${bridge}.`}>
      <rect className="bridge-box" x="1" y="20" width="176" height="40" rx="7" />
      <text className="bridge-cap" x="89" y="14" textAnchor="middle">IN ONE PROCESS</text>
      <text className="bridge-txt" x="89" y="45" textAnchor="middle">{name}</text>

      <line className="bridge-arrow" x1="182" y1="40" x2="272" y2="40" markerEnd="url(#bridge-tip)" />
      <text className="bridge-cap mid" x="227" y="32" textAnchor="middle">no shared memory</text>
      <text className="bridge-cap mid" x="227" y="56" textAnchor="middle">no shared clock</text>

      <rect className="bridge-box to" x="278" y="20" width="181" height="40" rx="7" />
      <text className="bridge-cap to" x="368" y="14" textAnchor="middle">ACROSS A NETWORK</text>
      <text className="bridge-txt to" x="368" y="45" textAnchor="middle">
        {bridge.length > 30 ? `${bridge.slice(0, 29)}…` : bridge}
      </text>

      <defs>
        <marker id="bridge-tip" viewBox="0 0 10 10" refX="9" refY="5"
                markerWidth="6" markerHeight="6" orient="auto-start-reverse">
          <path d="M0,0 L10,5 L0,10 z" className="bridge-tip" />
        </marker>
      </defs>
    </svg>
  )
}

export default function Patterns() {
  const [familyId, setFamilyId] = useState(CATALOGUE.families[0].id)
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState(CATALOGUE.families[0].patterns[0].name)

  const family = CATALOGUE.families.find(f => f.id === familyId) ?? CATALOGUE.families[0]

  // Searching spans every family -- looking for "retry" should not require
  // knowing which of five families it was filed under.
  const results = useMemo(() => {
    const q = query.trim().toLowerCase()
    if (!q) return family.patterns.map(p => ({ ...p, family: family.name }))
    return CATALOGUE.families.flatMap(f =>
      f.patterns
        .filter(p =>
          p.name.toLowerCase().includes(q) ||
          (p.what ?? '').toLowerCase().includes(q) ||
          (p.bridge ?? '').toLowerCase().includes(q))
        .map(p => ({ ...p, family: f.name })),
    )
  }, [query, family])

  const active = results.find(p => p.name === selected) ?? results[0] ?? null

  const total = CATALOGUE.families.reduce((n, f) => n + f.patterns.length, 0)

  return (
    <div className="patterns">
      <div className="pat-side">
        <input
          className="pat-search"
          type="search"
          placeholder={`Search ${total} patterns…`}
          value={query}
          onChange={e => setQuery(e.target.value)}
          aria-label="Search patterns"
        />

        {!query && (
          <div className="pat-fams">
            {CATALOGUE.families.map(f => (
              <button
                key={f.id}
                className={f.id === familyId ? 'tick on' : 'tick'}
                onClick={() => { setFamilyId(f.id); setSelected(f.patterns[0].name) }}
              >
                {f.name.replace('Gang of Four — ', 'GoF ')} <span>{f.patterns.length}</span>
              </button>
            ))}
          </div>
        )}

        <ul className="pat-list">
          {results.map(p => (
            <li key={`${p.family}-${p.name}`}>
              <button
                className={active && p.name === active.name ? 'pat-item on' : 'pat-item'}
                onClick={() => setSelected(p.name)}
              >
                <strong>{p.name}</strong>
                {query && <em>{p.family}</em>}
              </button>
            </li>
          ))}
          {!results.length && <li className="hint">Nothing matches “{query}”.</li>}
        </ul>
      </div>

      <div className="pat-detail">
        {!active && <p className="hint">Select a pattern.</p>}
        {active && (
          <>
            <h2>{active.name}</h2>
            <p className="pat-what">{active.what}</p>

            {active.bridge && (
              <div className="pat-bridge">
                <BridgeDiagram name={active.name} bridge={active.bridge} />
                <strong>{active.bridge}</strong>
                <p>{active.harder}</p>
              </div>
            )}

            <dl className="pat-fields">
              {active.where && (<><dt>Where</dt><dd>{active.where}</dd></>)}
              {active.how && (<><dt>How</dt><dd>{active.how}</dd></>)}
              {active.why && (<><dt>Why</dt><dd>{active.why}</dd></>)}
              {active.adv && (<><dt>Advantages</dt><dd>{active.adv}</dd></>)}
              {active.dis && (<><dt>Disadvantages</dt><dd>{active.dis}</dd></>)}
              {active.level && (<><dt>Difficulty</dt><dd>{active.level}</dd></>)}
            </dl>

            {active.tradeoff && (
              <p className="pat-tradeoff"><span>Trade-off</span> {active.tradeoff}</p>
            )}

            {active.top1 && (
              <div className="pat-top1">
                <span className="pat-top1-h">What the top 1% do differently</span>
                <p>{active.top1}</p>
              </div>
            )}

            {!active.top1 && (
              <p className="hint">
                Indexed here; the full entry lands as this family is written out. See the
                catalogue in the repository.
              </p>
            )}
          </>
        )}
      </div>
    </div>
  )
}
